### ISSUE TITLE
Warning pour data json innapropriés

### ISSUE THREAD

**Issue by qmorelCA** [cleverage/garden-starter-kit#12]
Il apparaît dans la console des warning pour tous les fichiers json qui ne sont pas trouvés qui ce soit pour les partials de pages, ou les partials de template "ui".

Avoir des warning pour les partials de pages non trouvés, ok mais pas nécessaire pour les autres templates (ui/layout).

![capture d ecran 2016-06-01 a 10 56 38](https://cloud.githubusercontent.com/assets/13568694/15705388/62a2dbe8-27ef-11e6-8585-9823ee4cd9b6.png)

**Comment by ryuran** [comment]
A twig partial file name should start with `_`.
If not, it's considered as a page.
