### ISSUE TITLE
Universalize Browserify

### ISSUE THREAD

**Issue by ryuran** [cleverage/garden-starter-kit#15]
Browserify use commonjs module natively.
But many plugin we use are not commonjs.

Find a way to use other modules format like AMD.

Maybe a good way :
http://dontkry.com/posts/code/browserify-and-the-universal-module-definition.html

Keep it configurable.

Seems to be around https://github.com/cleverage/garden-starter-kit/blob/master/.gsk/pipe/js/browserify.js#L49

**Comment by stephane-tessier** [comment]
https://github.com/cleverage/garden-starter-kit/pull/19
