### ISSUE TITLE
Add a sass-globbing support ?

### ISSUE THREAD

**Issue by Dotpeach** [cleverage/garden-starter-kit#22]
Well, dunno if I'm the only one around here, but I'm using sass-globbing to make lazy sass partials import : 
```
 // Éléments de l'interface utilisateur
  @import "07_ui/**";

  // Surcharge spécifique pour une page
  @import "08_pages/*";
```

So I'm always adding those lines in config.rb
```
# Require any additional compass plugins here.
require 'sass-globbing'
```

(C'est pas un VRAI soucis j'entends bien, surtout si je suis le seul à faire ça, mais je trouve ça bien pratique :) )

**Comment by ryuran** [comment]
Wouhou ! I'm waiting for your 2 lines pull request…

**Comment by ryuran** [comment]
Closed by doc #71
