### ISSUE TITLE
Gulp live doesn't detect new sass or twig partials

### ISSUE THREAD

**Issue by Dotpeach** [cleverage/garden-starter-kit#23]
Sass and Twig partials aren't always detected, I have to stop `gulp live --relax`and relaunch it to have my files compiled. (Well that's not a major issue, when you're used to it). 

Usages examples : 
### Twig : 
New file `_select.twig` in : `src/html/styleguide` 
Import `{% include '../styleguide/_select.twig' %}` in `src/html/page/my-page.twig`
__--> Not detected__ 

### Sass : 
New file `_select.scss` in : `src/css/ui` 
Import `@import "07_ui/**";` in `src/css/style.css`
__--> Not detected__ (maybe it's because I'm using Sass-globbing ? refs #22 )

**Comment by ryuran** [comment]
I think the wildcard for "watching" are not including this files

Yes, if you don't use Sass-globbing you must edit parent scss so the watcher will see it.

**Comment by stephane-tessier** [comment]
I checked but didn't find any quick solution about this... I'm afraid you'll have too keep on rebooting gulp live. :disappointed:

**Comment by stephane-tessier** [comment]
Bien vu

**Comment by stephane-tessier** [comment]
https://github.com/cleverage/garden-starter-kit/pull/36

**Comment by ryuran** [comment]
Du coup je ferme. c'est mergé
