### ISSUE TITLE
The doc task should be a Gulp live parameter

### ISSUE THREAD

**Issue by Dotpeach** [cleverage/garden-starter-kit#24]
GSK is way faster without the "doc" task. Yeah, I know, KSS is great, but we don't always need it, so it shouldn't be activate by default. 

Just like `gulp live --relax` a `gulp live --doc` seems to be a good way to have a live documentation option without making GSK slower most of the time.

**Comment by stephane-tessier** [comment]
https://github.com/cleverage/garden-starter-kit/pull/31
