### ISSUE TITLE
rework package.json

### ISSUE THREAD

**Issue by stephane-tessier** [cleverage/garden-starter-kit#32]
```
"devDependencies": {
    "autoprefixer": "^6.0.3",
    "babel-preset-es2015": "^6.3.13",
    "babelify": "^7.2.0",
    "browser-sync": "^2.9.10",
    "browserify": "^12.0.1",
    "del": "^2.0.2",
    "glob": "^5.0.15",
    "gulp": "^3.9.0",
    "gulp-a11y": "^0.1.1",
    "gulp-compass": "^2.1.0",
    "gulp-concat": "^2.6.0",
    "gulp-data": "^1.2.0",
    "gulp-dox": "^0.1.6",
    "gulp-hbs": "^0.2.0",
    "gulp-if": "^2.0.0",
    "gulp-imagemin": "^2.3.0",
    "gulp-jscs": "^3.0.2",
    "gulp-jshint": "^2.0.0",
    "gulp-less": "^3.0.3",
    "gulp-lesshint": "^1.0.0",
    "gulp-markdown": "^1.2.0",
    "gulp-newer": "^0.5.1",
    "gulp-plumber": "^1.0.1",
    "gulp-postcss": "^6.0.1",
    "gulp-prettify": "^0.3.0",
    "gulp-scss-lint": "^0.3.6",
    "gulp-sourcemaps": "^1.6.0",
    "gulp-stylint": "^3.0.0",
    "gulp-stylus": "^2.1.0",
    "gulp-twig": "^0.4.0",
    "gulp-uglify": "^1.4.2",
    "gulp-util": "^3.0.6",
    "highlight.js": "^8.9.1",
    "jshint": "^2.9.1",
    "jshint-stylish": "^2.0.1",
    "kss": "^2.1.1",
    "lazypipe": "^1.0.1",
    "nproxy": "stephane-tessier/nproxy#1.7.0",
    "require-dir": "^0.3.0",
    "run-sequence": "^1.1.4",
    "through2": "^2.0.0",
    "underscore": "^1.8.3",
    "vinyl-buffer": "^1.0.0",
    "vinyl-source-stream": "^1.1.0",
    "yargs": "^4.3.2"
  }
```

- [x] Différencier les `dependencies` et `devDependencies` (pas besoin d'installer de watcher sur une prod...)

- [x] Fixer les versions (plus sûr)

**Comment by ryuran** [comment]
@stephane-tessier, 

@JeremiePat me disait que browserify utilisait les “dependencies” pour le front.

Effectivement il faut fixer les version. Surtout pour tout ce qui peut bloquer le dev ou le build.

**Comment by stephane-tessier** [comment]
Non, browserify ne fait pas ça !

**Comment by stephane-tessier** [comment]
https://github.com/cleverage/garden-starter-kit/pull/35

**Comment by JeremiePat** [comment]
Effectivement, browserify se fiche de ou sont mis les dépendences. C'était juste une suggestion d'utiliser `dependencies` pour ce qui va effectivement être utile pour le front et d'utiliser `devDependencies`pour tout ce qui est build.

**Comment by ryuran** [comment]
à terme gsk sera une devDependency du projet. Donc l'organisation du package.json sera à revoir.
Mais à l'heure actuelle l'impact me semble négligeable.
Comme vous préférez.

**Comment by stephane-tessier** [comment]
Moi ça m'est égal, c'est vrai que ca permettrait d'y voir plus clair. D'un autre côté, si on maintient une doc des librairies utilisées, c'est suffisant aussi.

**Comment by ryuran** [comment]
Actuellement le starter kit est un outil de dev qui build un static, qui correspond à ce qui est livré, donc la prod. L'approche de @JeremiePat me parrait correspondre a cette idée. Les script front sont donc embarqués dans le build, mais pas ceux dédiés à concevoir ce build.

Ce sera à revoir le jour ou le gsk sera une devDependancy du projet et non pas intégré dans le projet comme aujourd'hui.

**Comment by stephane-tessier** [comment]
- soit le build est fait, et il n'y a rien a installer
- soit il faut faire le build et tu installes toutes les dépendances

Dans l'approche de @JeremiePat, il n'y pas de `npm install --prod`.
C'est pourquoi je préfère simplement documenter les libs utilisées par le front, et utiliser les devDependencies pour tout ce qui n'est pas *indispensable* au build de prod (watchers, nproxy, build html, linters...).

**Comment by ryuran** [comment]
Du coup c'est à discuter avec les équipes back.

**Comment by stephane-tessier** [comment]
C'est pas vraiment le ticket que j'ai envie de laisser traîner à cause des conflits... et je pense que tu peux toujours l'attendre ton retour des équipes back ^^
