### ISSUE TITLE
Rework task doc to use gulp-hb instead of gulp-hbs

### ISSUE THREAD

**Issue by ryuran** [cleverage/garden-starter-kit#38]
Since we use gulp-hbs as "handlebars template engine", we have 2 modules to do approximatively same thing.
To reduce dependencies number I think to remove dependency to gulp-hbs.
We need to rework doc:static task.

**Comment by stephane-tessier** [comment]
J'ai comparé les 2. Ce n'est pas simple.

Ca risque d'être chronophage pour un intérêt assez limité.

**Comment by okeul** [comment]
Hello !

Ce qui serait vraiment bien c'est que le moteur qui s'occupe de la génération de la doc soit indépendant par rapport au moteur de génération de template. Ou à minima le même histoire d'être cohérent. 

Si par exemple je pars sur du Twig, ce qui est le choix par défaut dans le GSK, c'est étrange d'avoir une doc généré en HBS. Il faudrait à minima que ça soit du Twig histoire d'être cohérent ou bien que ça soit neutre.

**Comment by ryuran** [comment]
Wontfix, prefer #128
