### ISSUE TITLE
Update : gulp-scss-lint to version 0.4.0

### ISSUE THREAD

**Issue by ryuran** [cleverage/garden-starter-kit#39]
To upgrade.

**Comment by nhoizey** [comment]
Vu qu'on est sur un projet open source, on pourrait brancher Greenkeeper : https://greenkeeper.io/

Exemple de PR qu'il a fait sur un de mes projets : https://github.com/esviji/esviji/commits?author=greenkeeperio-bot

**Comment by ryuran** [comment]
Fixed by #56
