### ISSUE TITLE
gulp help

### ISSUE THREAD

**Issue by ryuran** [cleverage/garden-starter-kit#40]
Make a 'gulp help'  commande (maybe as default) to help dev to find the good commande.
Because:

1. Dev do not read docs
2. I don't want search in doc when i'm on the terminal window
3. Easier for noob

**Comment by stephane-tessier** [comment]
https://github.com/cleverage/garden-starter-kit/pull/41

![gulp-help](https://cloud.githubusercontent.com/assets/2227881/16298881/ccadb324-3937-11e6-99d6-2e21912ade30.png)
