### ISSUE TITLE
allow specific build js for mobile and desktop

### ISSUE THREAD

**Issue by jchamois** [cleverage/garden-starter-kit#45]
Permet de ne pas compiler  les js inutile a tel ou tel device, et d ainsi ne charger que ce qui est nécessaire

**Comment by stephane-tessier** [comment]
Je ne suis pas convaincu de l'utilité de faire ça. Tu fais un site desktop + un site mobile, ou tu fais un site qui doit regarder la taille de l'écran et se comporter en fonction ?

**Comment by jchamois** [comment]
Hello, 
Par exemple tu as un carousel en desktop et qui en mobile est juste une liste d'items, tu n'auras ni besoin de charger le js qui init le carousel ni la lib du carousel lui meme. En l'occurence sur mon projet je me sert de match media pour init ou destroy mes instance en fonction des mq, mais dans tous les cas les ko de js sont chargé donc pas opti :-)

**Comment by stephane-tessier** [comment]
Donc si t'as un resize et que t'as besoin d'un carousel tu vas le charger sur le moment ?

**Comment by jchamois** [comment]
l'objectif est que sur mobile on n'ai moins de data a télécharger et moins de script a éxécuter.
Le cas resize sous entend que tu es de toute façon sur desktop, et que ton script est dispo. tu n'as plus qu'a l init sur un matchmedia par exemple

**Comment by nhoizey** [comment]
@jchamois passer de portrait à paysage sur un smartphone ou une tablette peut provoquer un resize

**Comment by jchamois** [comment]
Oui par exemple sur mon projet j init ou destroy un carrousel sur un match media, car le resize du browser autorise de switcher les affichage a  la volée (comme un orientation change) neanmoins sur un mobile portrait ou landscape je n'ai à aucun moment besoin de ma lib de carousel et du script qui d init qui va avec :-) et c'est valable pour différentes briques de js, comme des polyfill, ou d'autre fonctionnalités.

**Comment by stephane-tessier** [comment]
https://github.com/cleverage/garden-starter-kit/pull/57
