### ISSUE TITLE
Add a conditional loader for specific js build

### ISSUE THREAD

**Issue by jchamois** [cleverage/garden-starter-kit#46]
Permet de charger le bon fichier en fonction du device (doit etre largement possible avec browserify, du coup un exemple serait top)

**Comment by stephane-tessier** [comment]
C'est en lien avec https://github.com/cleverage/garden-starter-kit/issues/45 ?

**Comment by ryuran** [comment]
Je pense qu'il faut effectivement gérer le #45 et que ce sera au dev js du projet de faire le loader conditionel coté js (c'est pas propre au starterkit mais au projet du coup)

**Comment by nhoizey** [comment]
Ne peut-on pas utiliser le plugin [jQuery Dependencies](https://github.com/cleverage/ca.jquery.dependencies) de Jérémie, voire essayer d'en faire une version ne nécessitant pas jQuery ?

**Comment by stephane-tessier** [comment]
Je suis assez d'accord pour dire que la problématique est extérieure au starter kit.

**Comment by jchamois** [comment]
Pour moi si le starter Kit permet de générer plusieurs build js différents, il devrait aussi prévoir la mécanique pour les appeler selon les conditions de ces builds.  comme pour un wiredep par exemple

**Comment by ryuran** [comment]
Starterkit <= outils pour builder le front

Ce dont tu parles => logique front => donc dans la brique projet

**Comment by jchamois** [comment]
Tu demande a ton outil de builder 2 js différents en fonction d'une config. donc pour moi il est logique que l 'outil te fasse un output  avec la mecanique de chargement associé au build.
Du coup ca voudrait dire que ton config json, tu applique une config de output conditional, et que dans ton js de projet, tu "dupliques" config :-/

**Comment by stephane-tessier** [comment]
Tes fichiers JS ne dépendent pas de la conf, ils dépendent des imports que tu fais dedans.

**Comment by ryuran** [comment]
Avec Webpack tu peux faire un fichier script qui va charger un bundle suivant une mediaquery.

Avec une combinaison de matchmedia et require.ensure() tu devrais pouvoir répondre à ton besoin.
