### ISSUE TITLE
Quick fix for _default.twig

### ISSUE THREAD

**Issue by Krakysis** [cleverage/garden-starter-kit#47]
Line 7 in [src/html/layouts/_default.twig](https://github.com/cleverage/garden-starter-kit/blob/master/src/html/layouts/_default.twig)
> \<meta http-equiv="X-UA-Compatible" content="IE=edge,**chrome=1**">

You should remove **chrome=1** in this meta as Google frame is retired.
It's a really small issue and probably not important, but it is reported as an error on the W3C Markup validator tool.

See: [Google frame is no longer supported and retired](https://www.chromium.org/developers/how-tos/chrome-frame-getting-started)

**Comment by stephane-tessier** [comment]
https://github.com/cleverage/garden-starter-kit/pull/54
