### ISSUE TITLE
Gestion des JS

### ISSUE THREAD

**Issue by qmorel** [cleverage/garden-starter-kit#5]
Actuellement, tous les fichier JS présent dans src/js sont concaténer en fonction de l'ordre alphabétique des fichiers.

L'idéale serait de gérer les JS via les import ES6, enfin de pouvoir créer un ou plusieurs JS séparer et non plus avoir un seul fichier avec tout de concaténer.

Il serait idéal aussi de pouvoir séparer des JS issue de sources client (si l'ont doit reprendre des JS d'une version desktop pour un inté mobile) afin de ne pas polluer le JS mobile dédié.

Je n'ai pas regarder en détail le fonctionnement de la gestion actuelle des JS, mais ça parait contraignant.

**Comment by ryuran** [comment]
Salut

J'ai regardé un peu le code.

```js
var SRC  = [
  path.join(ENV.js['src-dir'], 'lib', '**', '*'),
  path.join(ENV.js['src-dir'], '**', '*')
];
```

Pour le moment gsk 2 concatène les fichiers js en commençant par les js du dossier lib/
puis les autres (d'ailleurs le dossier li n'est pas exclue des autres, c'est bizarre).

Pour régler le problème il faudrait rendre cette variable SRC configurable dans le config.json
Ce qui permettrai de définir l'ordre des js.

**Comment by stephane-tessier** [comment]
https://github.com/cleverage/garden-starter-kit/pull/8
```

Quelque chose comme ça ?

"js" : {
    "src-dir"  : "./src/js",
    "dest-dir" : "./build/js",
    "engine"   : "copy",
    "filename" : "script.js",
    "src"      : [
      "./src/js/lib/somelib.js",
      "./src/js/mymodule.js"
    ]
  }
```

**Comment by ryuran** [comment]
`src-dir` sert encore su on a une list en `src`

"js" : {
    "dest-dir" : "./build/js",
    "engine"   : "copy",
    "filename" : "script.js",
    "src"      : [
      "./src/js/lib/main.js",
      "./src/js/lib/**/*.js",
      "./src/js/**/*.js"
    ]
  }

En ordonnant et dédupliquant les fichier qui match.

**Comment by stephane-tessier** [comment]
oui, le linter va linter les fichiers dans le dossier js sauf ceux qui sont dans le dossier lib, donc faut les deux

**Comment by ryuran** [comment]
```
"js" : {
    "src-dir" : "./src/js",
    "dest-dir" : "./build/js",
    "engine"   : "copy",
    "filename" : "script.js",
    "src"      : [
      "lib/main.js",
      "lib/**/*.js",
      "**/*.js"
    ]
  }
```

comme ça alors en faisant partir les patern de path depuis le "src-dir" ?

**Comment by stephane-tessier** [comment]
Comme tu veux ☺
Les chemins complet ça pourrait permettre de charger une lib qui soit ailleurs, genre un module node.

**Comment by ryuran** [comment]
Un engine copy et concat a été crée avec la possibilité de surcharger l'ordre via la config.
Cependant nous recommandons l'utilisation de browserify ce qui ne produirai pas ce soucis.
