### ISSUE TITLE
uglify fails in concat with gif()

### ISSUE THREAD

**Issue by jchamois** [cleverage/garden-starter-kit#50]
issue with the line  .pipe(gif(ENV.all.optimize, uglify())) in the concat.js  task. 
It doesn't uglify, so I remove gif function :  .pipe(uglify()) and it works.

The var ENV.all.optimize return the right value, according to the config (boolean).

**Comment by stephane-tessier** [comment]
Pour l'instant je ne reproduis pas. Chez moi c'est ok avec les exemples du GSK.

**Comment by ryuran** [comment]
On ne va pas garder concat comme builder js.
Il n'avait été utilisé uniquement pour contourner des limitation de browserify qui n'ont plus lieux d'être avec webpack.
