### ISSUE TITLE
Sub Sass folder compilation error

### ISSUE THREAD

**Issue by qmorel** [cleverage/garden-starter-kit#52]
Add sub-folder in the Sass folder an error at compilation:
`[15:57:49] Starting 'test:css'...
^[[A[15:57:51] Finished 'test:css' after 2.23 s
[15:57:51] Starting 'css'...
[ERROR] uncaughtException: Cannot read property 'type' of null`

Seems to come from PostCSS, an upgrade to 6.1.1 solve the problem.

**Comment by ryuran** [comment]
You can rename your subdirectory with `_` at start to solve this issue.

**Comment by stephane-tessier** [comment]
https://github.com/cleverage/garden-starter-kit/pull/55
