### ISSUE TITLE
wait for the end of compiling (sass, twig ...) to refresh browser

### ISSUE THREAD

**Issue by jchamois** [cleverage/garden-starter-kit#59]
Browser sync is refreshing too early before the end of sass and twig are done.

**Comment by stephane-tessier** [comment]
Works for me :/

I'm on the branch NCU (https://github.com/cleverage/garden-starter-kit/pull/56), and can't switch my modules coz i have a shitty proxied network here..

Can't you confirm you still have the issue on NCU branch?
Can anyone else confirm the issue?

**Comment by jchamois** [comment]
IT worked well at the beginning of my project, but not now so I guess it works with small files when compiling is fast. Can you test with large file or project?

**Comment by stephane-tessier** [comment]
to try:
https://github.com/vigetlabs/gulp-starter/pull/306
