### ISSUE TITLE
Gulp fontello

### ISSUE THREAD

**Issue by ryuran** [cleverage/garden-starter-kit#6]
Ajouter une tâche pour les fonts de glyphes fontello.
Afin de facilité la migration de projet sous le starter kit v1

**Comment by okeul** [comment]
La plupart des projets sur le GSK v1 ne ferons pas la migration vers la dernière version pour pleins d'autres raisons. A mon sens il y a trop de différence. Et puis les font d'icônes c'est _hasbeen_.

**Comment by ryuran** [comment]
We should not use web icon font and prefer SVG.
