### ISSUE TITLE
Gulp svg symboles

### ISSUE THREAD

**Issue by ryuran** [cleverage/garden-starter-kit#7]
Ajouter une tache pour la gestions des symbols svg.
A préférer aux font quand le scope navigateur projet le permet.

**Comment by stephane-tessier** [comment]
Quel est exactement le besoin ?

- Un tag <svg> dans le HTML et utiliser le tag <use> ?
https://github.com/w0rm/gulp-svgstore
- Sprite svg ?
https://github.com/jkphl/gulp-svg-sprite
- Sprite svg avec fallback png ?
https://github.com/jkphl/iconizr

**Comment by nhoizey** [comment]
> A préférer aux font quand le scope navigateur projet le permet

Donc toujours… :-p

**Comment by nhoizey** [comment]
@stephane-tessier `gulp-svgstore` + `gulp-inject` FTW!

**Comment by stephane-tessier** [comment]
Quel serait l'intérêt par rapport à contribuer le svg directement dans le layout twig/hbs ?

**Comment by nhoizey** [comment]
Garder les différents SVG indépendants, pour les mettre à jour individuellement selon les besoins.

**Comment by stephane-tessier** [comment]
https://github.com/cleverage/garden-starter-kit/pull/34

**Comment by ryuran** [comment]
J'avais un svgstore + un helper (twig/hbs) readFile.

Gulp-inject apporte quoi ? pourra t'on intégre la liste des symboles dans la doc KSS ?
@stephane-tessier

**Comment by stephane-tessier** [comment]
svgstore regroupe les svg, puis gulp-inject l'ajoute dans le html

pour la liste des symboles je ne suis pas sûr ? ca doit ressembler à quoi ? être dans les fichiers scss ?

**Comment by stephane-tessier** [comment]
@nhoizey 
> Il faut sans doute déterminer comment gérer les fallback PNG pour les cas où on doit supporter IE8

Générer le fichier png sprite correspondant et les mettres en background pour IE8 ?

**Comment by nhoizey** [comment]
Avec [gulpicon](https://github.com/filamentgroup/gulpicon) si c'est compatible, oui.

Ou alors, on décide tout simplement que le sujet IE8 n'est pas traité dans le GSK v2, et on avance plus facilement.

**Comment by stephane-tessier** [comment]
Etant donné l'arrêt du support de IE < 11 de la part Microsoft depuis janvier, je serai tenté de dire qu'on avance.

**Comment by nhoizey** [comment]
Ce n'est pas si simple, par exemple encore 30% de IE6/7/8 en Chine si on croit les stats de Baidu, mais oui, il faut avancer, gérer le support de IE8 est vraiment un trop gros frein à pas mal de choses.

A-t-on lancer des projets d'inté front il y a moins d'un an avec le support IE8 dans les contraintes ?

**Comment by ryuran** [comment]
Oui mais ils ont vite abandonné le support. Souvent avant la première mise en prod.
C'est souvent le parc interne qui était sur IE8 qui était en train de se mettre à jour.

Si on a le support IE8 je me demande si c'est une bonne solution de partir sur svg.
J'avais utilisé svgtoolkit sur starterkit v1 pour générer les fallback png mais c'est très contraignant puisque pour une icon svg il faut plusieurs png de fallback à cause du manque de scalabilité et style de couleur sur le png.

Pour moi si on a "support IE8" la font d'icon me parait une option plus gérable et surtout facile à remplacer par des svg par la suite le jour où le support IE8 sautera (2 ou 3 jour de travail max si on a les svg d'origine).

**Comment by nhoizey** [comment]
Je veux bien être d'accord qu'utiliser une fonte pour IE8 est plus simple.

Mais la question reste plutôt ma précédente : est-il pertinent de gérer le support IE8 de base dans le GSK v2 ?

@fcharlot : est-ce qu'on fait encore, ces derniers mois, des propales incluant le support de IE8 ?

**Comment by stephane-tessier** [comment]
De toutes façons ce serait dommage de dire qu'à cause d'IE8 on n'abandonne la feature, non ?
Donc on merge et pour les cas particuliers on débranchera à la main.

**Comment by ryuran** [comment]
de toute façon il faut la feature. la question est "Faut'il un fallback ?" et ça on verra si besoin réel.

**Comment by nhoizey** [comment]
@ryuran je vois que tu vires gulp-inject au profit de Twig.

gulp-inject a pourtant le mérite de fonctionner aussi ensuite, quand l'inté est intégrée dans le projet final, même s'il n'utilise pas Twig.

Du coup je doute… ;-)

**Comment by ryuran** [comment]
Fix by #34
